FROM java:8
MAINTAINER Pavel Katsuba <kets911@gmail.com>
ADD aut-java-lab-2018-pavel-katsuba-1.0-jar-with-dependencies.jar .
VOLUME /opt/
CMD ["java", "-jar", "aut-java-lab-2018-pavel-katsuba-1.0-jar-with-dependencies.jar", "/opt/"]